blank_issues_enabled: true
contact_links:
  - name: вопросы
    url: https://github.com/g110ssiness/MyFirstProject/discussions
    about: тут можете задать вопросы

issue_templates:
  - bug_report.md
  - feature_request.md

